export type Template = {
  id: string;
  name: string;
  category: "SaaS" | "Portfolio" | "Landing Page" | "Startup";
  tech: string[];
  thumbnail: string;
  previewUrl: string;
  downloadUrl: string;
  downloads: number;
  stars: number;
  featured: boolean;
  createdAt: string;
};

export const templates: Template[] = [
  {
    id: "1",
    name: "SaaSify",
    category: "SaaS",
    tech: ["Next.js", "React"],
    thumbnail: "https://placehold.co/600x400/6366f1/ffffff?text=SaaSify",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 1240,
    stars: 87,
    featured: true,
    createdAt: "2025-01-10",
  },
  {
    id: "2",
    name: "Folio Pro",
    category: "Portfolio",
    tech: ["Next.js", "React"],
    thumbnail: "https://placehold.co/600x400/22c55e/ffffff?text=Folio+Pro",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 980,
    stars: 64,
    featured: true,
    createdAt: "2025-02-14",
  },
  {
    id: "3",
    name: "LaunchKit",
    category: "Landing Page",
    tech: ["Next.js", "React"],
    thumbnail: "https://placehold.co/600x400/f59e0b/ffffff?text=LaunchKit",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 2100,
    stars: 143,
    featured: true,
    createdAt: "2025-03-01",
  },
  {
    id: "4",
    name: "StartupBase",
    category: "Startup",
    tech: ["Next.js", "React"],
    thumbnail: "https://placehold.co/600x400/ec4899/ffffff?text=StartupBase",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 760,
    stars: 52,
    featured: true,
    createdAt: "2025-03-20",
  },
  {
    id: "5",
    name: "DashFlow",
    category: "SaaS",
    tech: ["Next.js", "React"],
    thumbnail: "https://placehold.co/600x400/6366f1/ffffff?text=DashFlow",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 540,
    stars: 38,
    featured: false,
    createdAt: "2025-04-05",
  },
  {
    id: "6",
    name: "MinimalCV",
    category: "Portfolio",
    tech: ["HTML/CSS"],
    thumbnail: "https://placehold.co/600x400/22c55e/ffffff?text=MinimalCV",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 430,
    stars: 29,
    featured: false,
    createdAt: "2025-04-12",
  },
  {
    id: "7",
    name: "ProductHunt Clone",
    category: "Startup",
    tech: ["Next.js", "React"],
    thumbnail: "https://placehold.co/600x400/ec4899/ffffff?text=PH+Clone",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 890,
    stars: 71,
    featured: false,
    createdAt: "2025-04-18",
  },
  {
    id: "8",
    name: "AgencyOne",
    category: "Landing Page",
    tech: ["HTML/CSS"],
    thumbnail: "https://placehold.co/600x400/f59e0b/ffffff?text=AgencyOne",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 670,
    stars: 44,
    featured: false,
    createdAt: "2025-05-01",
  },
  {
    id: "9",
    name: "CloudSaaS",
    category: "SaaS",
    tech: ["React"],
    thumbnail: "https://placehold.co/600x400/6366f1/ffffff?text=CloudSaaS",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 310,
    stars: 21,
    featured: false,
    createdAt: "2025-05-10",
  },
  {
    id: "10",
    name: "DevPortfolio",
    category: "Portfolio",
    tech: ["Next.js", "React"],
    thumbnail: "https://placehold.co/600x400/22c55e/ffffff?text=DevPortfolio",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 1050,
    stars: 88,
    featured: false,
    createdAt: "2025-05-20",
  },
  {
    id: "11",
    name: "VentureX",
    category: "Startup",
    tech: ["Next.js"],
    thumbnail: "https://placehold.co/600x400/ec4899/ffffff?text=VentureX",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 480,
    stars: 33,
    featured: false,
    createdAt: "2025-06-01",
  },
  {
    id: "12",
    name: "ConvertPage",
    category: "Landing Page",
    tech: ["HTML/CSS"],
    thumbnail: "https://placehold.co/600x400/f59e0b/ffffff?text=ConvertPage",
    previewUrl: "https://example.com",
    downloadUrl: "#",
    downloads: 720,
    stars: 55,
    featured: false,
    createdAt: "2025-06-10",
  },
];

export const categories = [
  { name: "SaaS", icon: "LayoutDashboard", count: templates.filter((t) => t.category === "SaaS").length },
  { name: "Portfolio", icon: "User", count: templates.filter((t) => t.category === "Portfolio").length },
  { name: "Landing Page", icon: "Rocket", count: templates.filter((t) => t.category === "Landing Page").length },
  { name: "Startup", icon: "Zap", count: templates.filter((t) => t.category === "Startup").length },
] as const;
